export const Assets = {
    images: {
        closed: '/image/close.png',
        email: '/image/email.png',
        facebook: '/image/face.svg',
        flechaDiagonal: '/image/flecha-hacia-arriba.svg',
        flechaAbajo: '/image/icon.svg',
        flechaArriba: '/image/icon1.svg',
        imageCojinesGlo: '/image/image1.jpg',
        imageSanta: '/image/image2.jpg',
        imageCojinDorado: '/image/image3.jpg',
        imageCojinSet: '/image/image4.jpg',
        imageCojinStart: '/image/start.jpg',
        home: '/image/home.png',
        instagram: '/image/instagram.svg',
        login: '/image/login.png',
        imagePinguino: '/image/pinguino.jpg',
        imagePizza: '/image/pizza.jpg',
        imageSantaNew: '/image/santa.jpg',
        menu: '/image/menu.png',
        twitter: '/image/twitter.svg',
        username: '/image/username.png',
        spiderman: '/image/spiderman.jpg',
        youtube: '/image/youtube.svg',
        loginAccess: '/image/login-access.png',
        register: '/image/register.png',
        product: '/image/product.png',
        logo: '/image/logo.gif',
        logoStatic: '/image/SarahiStyles.png',
    },
};
